models/User.php
<?php

namespace app\models;

use rmrevin\yii\module\Comments\interfaces\CommentatorInterface;
use Yii;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;
use yii\web\UploadedFile;

/**
 * This is the model class for table "user".
 *
 * @property int $id
 * @property string $user_type тип
 * @property string $login Логин
 * @property string $name ФИО
 * @property string $email email
 * @property string $email_password Email пароль
 * @property string $phone телефон
 * @property string $birth_date дата рождения
 * @property string $avatar Аватар
 * @property string $password_hash Зашифрованный пароль
 * @property int $is_deletable Можно удалить или нельзя
 * @property string $created_at
 * @property string $info
 * @property string $color
 * @property integer $role
 * 'color','role'
 *
 * @property UploadedFile $file
 *

 */
class User extends ActiveRecord implements IdentityInterface, CommentatorInterface
{
    const SCENARIO_DEFAULT = 'default';
    const SCENARIO_EDIT = 'edit';

    const ROLE_ADMIN = 1;
    const ROLE_MANAGER = 2;
    const ROLE_CUTTING = 3;
    const ROLE_BEND = 4;
    const ROLE_PAINTING = 5;
    const ROLE_WELDING = 6;
    const ROLE_DIRECTOR = 7;


    public $password;

    public $user_type;


    public $file;

    private $oldPasswordHash;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * @inheritdoc
     */
    public function scenarios()
    {
        return [
            self::SCENARIO_DEFAULT => [
                'name', 'login', 'email_password', 'is_deletable',
                'info', 'password', 'password_hash',
                'phone', 'address', 'birth_date', 'avatar','color','role'],
            self::SCENARIO_EDIT => [
                'name', 'login', 'email_password', 'type', 'is_deletable', 'password',
                'info', 'password_hash', 'role', 'city_id',
                'phone', 'birth_date', 'avatar','color'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['login', 'name'], 'required'],
            [['password'], 'required', 'on' => self::SCENARIO_DEFAULT],
            ['birth_date', function () {
                if ($this->birth_date > date('Y-m-d') or strlen($this->birth_date) > 10) {
                    $this->addError('birth_date', 'Некорректная дата');
                    return false;
                }
                return true;
            }],
            ['login', 'email'],
            [['login'], 'unique'],
            ['file', 'file'],
            [['is_deletable','role'], 'integer'],
            [['login', 'password_hash', 'password', 'name', 'avatar','color', 'email_password'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function beforeDelete()
    {
        parent::beforeDelete();

        /** @var User $identity */
        $identity = Yii::$app->user->identity;

        $uid = $identity->id;

        if ($uid == $this->id) {
            Yii::$app->session->setFlash('error', "Вы авторизованы под пользователем «{$this->login}». Удаление невозможно!");
            return false;
        }

        if ($this->is_deletable == false) {
            Yii::$app->session->setFlash('error', "Этот пользователь не может подлежать удалению. Удаление невозможно!");
            return false;
        } else {
            return true;
        }
    }

    public function getCommentatorAvatar()
    {
        return '/' . $this->getRealAvatar();
    }

    public function getCommentatorName()
    {
        return $this->name;
    }

    public function getCommentatorUrl()
    {
        return ['user/view', 'id' => $this->id]; // or false, if user does not have a public page
    }

    /**
     * @return string
     */
    public function getRealAvatar()
    {
        return $this->avatar != null ? $this->avatar : 'img/nouser.png';
    }

    /**
     * @return bool
     */
    public function isSuperAdmin()
    {
        return $this->role === self::ROLE_ADMIN;
    }

    /**
     * @inheritdoc
     */
    public function afterFind()
    {
        $this->oldPasswordHash = $this->password_hash;
    }


    /**
     * @inheritdoc
     */
    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            if ($this->file != null) {
                $fileName = Yii::$app->security->generateRandomString();
                if (is_dir('upload') == false) {
                    mkdir('upload');
                }
                $path = "uploads/{$fileName}.{$this->file->extension}";
                $this->file->saveAs($path);
                if ($this->file != null && file_exists($this->file)) {
                    unlink($this->file);
                }
                $this->avatar = $path;
            }

            if ($this->isNewRecord) {
                $this->created_at = date('Y-m-d H:i:s');
            }
            if ($this->password != null) {
                $this->password_hash = Yii::$app->security->generatePasswordHash($this->password);
            } else {
                $this->password_hash = $this->oldPasswordHash;
            }


            return true;
        }
        return false;
    }


    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'login' => 'Email',
            'name' => 'ФИО',
            'email' => 'Email',
            'phone' => 'Номер телефона ',
            'type' => 'Тип пользователя',
            'birth_date' => 'Дата рождения',
            'file' => 'Фотография',
            'avatar' => 'Фотография',
            'password_hash' => 'Password Hash',
            'is_deletable' => 'Можно ли удалять',
            'created_at' => 'Дата создания',
            'info' => 'Информация',
            'email_password' => 'Пароль от Email',
            'color' => 'Цвет',
            'role' => 'Роль'
        ];
    }

    /**
     * @return array
     */
    public static function roleLabels()
    {
        return [
            self::ROLE_ADMIN => 'Администратор CRM',
            self::ROLE_MANAGER =>  'Менеджер',
            self::ROLE_CUTTING => 'Резка',
            self::ROLE_BEND => 'Гибка',
            self::ROLE_PAINTING => 'Покраска',
            self::ROLE_WELDING => 'Сварка',
            self::ROLE_DIRECTOR => 'Начальник цеха'
        ];
    }

    /**
     * @inheritdoc
     * @return UserQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new UserQuery(get_called_class());
    }

    public static function findIdentity($id)
    {
        return static::findOne($id);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        foreach (self::$users as $user) {
            if ($user['accessToken'] === $token) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['login' => $username]);
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->password;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->authKey === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    public function setPassword($password)
    {
        $this->password = $password;
    }



}

views/user/_columns.php
<?php

use app\models\City;
use app\models\Role;
use kartik\grid\GridView;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;

return [
    [
        'class' => 'kartik\grid\CheckboxColumn',
        'width' => '20px',
    ],
        // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'id',
    // ],


    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'name',
        'content' => function($model){
            return Html::a($model->name, ['view', 'id' => $model->id], ['data-pjax' => '0']);
        }
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'email',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'phone',
    ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'birth_date',
     ],

     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'info',
     ],
    [
        'attribute' => 'color',
        'value' => function ($model, $key, $index, $widget) {
            return "<span class='badge'  style='background-color: {$model->color}'> </span>  ";
        },
        'width' => '',
        'filterType' => GridView::FILTER_COLOR,
        'filterWidgetOptions' => [
            'showDefaultPalette' => true,
        ],
        'vAlign' => 'middle',
        'format' => 'raw',
    ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'role',
         'content' =>function($data){

             if ($data->role == '1') {
                 return 'Администратор CRM';
             }
             if ($data->role == '2') {
                 return 'Менеджер';
             }
             if ($data->role == '3') {
                 return 'Резка';
             }
             if ($data->role == '4') {
                 return 'Гибка';
             }
             if ($data->role == '5') {
                 return 'Покраска';
             }
             if ($data->role == '6') {
                 return 'Сварка';
             }
             if ($data->role == '7') {
                 return 'Начальник цеха';
             }
             return 'не заданно';
         },

         'filter'=>array(
             '1' => 'Администратор CRM',
             '2' =>  'Менеджер',
             '3' => 'Резка',
             '4' => 'Гибка',
             '5' => 'Покраска',
             '6' => 'Сварка',
             '7' => 'Начальник цеха'
         ),

     ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'is_deletable',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'created_at',
    // ],
    [
        'class' => 'kartik\grid\ActionColumn',
        'dropdown' => false,
        'template' => '{view}{update}{delete}',
        'vAlign'=>'middle',
        'urlCreator' => function($action, $model, $key, $index) {
                return Url::to([$action,'id'=>$key]);
        },

//        'viewOptions'=>['role'=>'modal-remote','title'=>'View','data-toggle'=>'tooltip'],
        'updateOptions'=>['role'=>'modal-remote','title'=>'Изменить', 'data-toggle'=>'tooltip'],
        'deleteOptions'=>['role'=>'modal-remote','title'=>'Удалить',
                          'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                          'data-request-method'=>'post',
                          'data-toggle'=>'tooltip',
                          'data-confirm-title'=>'Вы уверены?',
                          'data-confirm-message'=>'Вы действительно хотите удалить данный элемент?'],
    ],

];

views/user/_form.php
<?php

use app\models\User;
use kartik\color\ColorInput;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use unclead\multipleinput\MultipleInput;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */

?>
<?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

<div class="user-form">
    <div class="modal-teo">

        <div class="row">
            <div class="col-md-4">
                <div class="avatar" style="height: 250px;width:250px;background-image:url(avatars/avatar.png);background-position: center;"></div>
            </div>
            <div class="col-md-8">
                <div class="row">
                    <div class="col-md-8">
                        <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
                    </div>
                    <div class="col-md-4">
                        <?= $form->field($model, 'birth_date')->input('date') ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="row">
                            <div class="col-md-6">
                                <?= $form->field($model, 'login')->textInput() ?>
                            </div>
                            <div class="col-md-6">
                                <?= $form->field($model, 'email_password')->textInput() ?>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <?= $form->field($model, 'password')->passwordInput() ?>
                    </div>
                    <div class="col-md-4">
                        <?= $form->field($model, 'phone')->widget(\yii\widgets\MaskedInput::class, [
                            'mask' => '+7 999 999-99-99',
                        ]) ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <?= $form->field($model, 'color')->widget(ColorInput::classname(), [
                            'options' => ['placeholder' => 'Выберите цвет ...'],
                        ]); ?>
                    </div>
                    <div class="col-md-4">
                        <?= $form->field($model, 'role')->dropDownList(User::roleLabels()) ?>
                    </div>
                </div>

                <div class="col-md-12">
                    <?= $form->field($model, 'info')->textarea(['rows' => 4]) ?>
                </div>
            </div>

        </div>

        <div class="row">
            <div class="col-md-3">
                <?= $form->field($model, 'file')->fileInput() ?>
            </div>
        </div>




        <?php if (!Yii::$app->request->isAjax){ ?>
            <div class="form-group">
                <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
            </div>
        <?php } ?>

    </div>


    <?php ActiveForm::end(); ?>

views/user/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\User */

?>
<div class="user-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/user/index.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use kartik\grid\GridView;
use johnitvn\ajaxcrud\CrudAsset;
use app\widgets\BulkButtonWidget;

/* @var $this yii\web\View */

/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = "Пользователи";
$this->params['breadcrumbs'][] = $this->title;

CrudAsset::register($this);

?>
<div class="panel panel-inverse position-index">
    <div class="panel-heading">
        <!--        <div class="panel-heading-btn">-->
        <!--        </div>-->
        <h4 class="panel-title">Пользователи</h4>
    </div>
    <div class="panel-body">
        <div id="ajaxCrudDatatable">
            <?=GridView::widget([
                'id'=>'crud-datatable',
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'pjax'=>true,
                'columns' => require(__DIR__.'/_columns.php'),
                'panelBeforeTemplate' =>    Html::a('Добавить <i class="fa fa-plus"></i>', ['create'],
                        ['role'=>'modal-remote','title'=> 'Добавить пользователя','class'=>'btn btn-success']).'&nbsp;'.
                    Html::a('<i class="fa fa-repeat"></i>', [''],
                        ['data-pjax'=>1, 'class'=>'btn btn-white', 'title'=>'Обновить']),
                'striped' => true,
                'condensed' => true,
                'responsive' => true,
                'panel' => [
                    'headingOptions' => ['style' => 'display: none;'],
                    'after'=>BulkButtonWidget::widget([
                            'buttons'=>Html::a('<i class="glyphicon glyphicon-trash"></i>&nbsp; Удалить',
                                ["bulk-delete"] ,
                                [
                                    "class"=>"btn btn-danger btn-xs",
                                    'role'=>'modal-remote-bulk',
                                    'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                                    'data-request-method'=>'post',
                                    'data-confirm-title'=>'Вы уверены?',
                                    'data-confirm-message'=>'Вы действительно хотите удалить данный элемент?'
                                ]),
                        ]).
                        '<div class="clearfix"></div>',
                ]
            ])?>
        </div>
    </div>
</div>

<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    'options' => ['class' => 'fade modal-slg'],
    "footer"=>"",// always need it for jquery plugin
])?>
<?php Modal::end(); ?>

views/user/profile.php
<?php

use app\models\User;
use yii\widgets\ActiveForm;

/**
 * @var $model User
 */


$this->title = 'Профиль';

?>

    <div class="panel panel-inverse">
        <div class="panel-heading">
            <h4 class="panel-title">Настройки</h4>
        </div>
        <div class="panel-body">
            <?php $form = ActiveForm::begin() ?>

            <div class="row">
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-12">
                            <?= $form->field($model, 'name')->textInput() ?>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <?= $form->field($model, 'login')->textInput() ?>
                        </div>
                        <div class="col-md-6">
                            <?= $form->field($model, 'password')->passwordInput() ?>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <?= $form->field($model, 'phone')->textInput() ?>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <?= \yii\helpers\Html::submitButton('<i class="fa fa-check"></i> Сохранить', ['class' => 'btn btn-success']) ?>
                        </div>
                    </div>

                </div>

                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-12">
                            <img class="circle-img" style="height: 250px; width: 250px; border-radius: 100%; object-fit: contain; border: 2px solid #cecece; cursor: pointer;" src="/<?=$model->getRealAvatar()?>" data-role="profile-image-select">
                        </div>
                    </div>
                </div>
            </div>

            <?php ActiveForm::end() ?>
        </div>
    </div>

<?php

$script = <<< JS
    $('[data-role="profile-image-select"]').click(function(){
        $('#avatar-form input').trigger('click');
    });

    $('#avatar-form input').change(function(){
        $('#avatar-form').submit();
    });
    
    $('#avatar-form').submit(function(e){
        var formData = new FormData(this);
        $.ajax({
            type: "POST",
            url: $('#avatar-form').attr('action'),
            data: formData,
            contentType: false,
            cache: false,
            processData: false,
            success: function(response){
                if(response.success === 1){
                    var path = '/'+response.path;
                    $('[data-role="avatar-view"]').each(function(i){
                        $(this).attr('src', path);
                    });
                    $('[data-role="profile-image-select"]').each(function(i){
                        $(this).attr('src', path);
                    });
                }
            }
        });
        e.preventDefault();
    });
JS;

$this->registerJs($script, \yii\web\View::POS_READY);


?>

views/user/reset-password-form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\forms\ResetPasswordForm */
/* @var $form ActiveForm */
?>

<?php $form = ActiveForm::begin(); ?>

<?= $form->field($model, 'newPassword') ?>
<?= $form->field($model, 'repeatPassword') ?>

<?php if(!Yii::$app->request->isAjax): ?>
    <div class="form-group">
        <?= Html::submitButton('Изменить', ['class' => 'btn btn-primary']) ?>
    </div>
<?php endif; ?>

<?php ActiveForm::end(); ?>

views/user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User */
?>
<div class="user-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/user/view.php
<?php


use yii\bootstrap\Modal;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User */

?>
<div class="user-view">

    <div class="panel panel-inverse">
        <?php Pjax::begin(['id' => 'pjax-container-info-container', 'enablePushState' => false]); ?>
        <div class="panel-heading">
            <h4 class="panel-title">Информация</h4>
            <div class="panel-heading-btn" style="margin-top: -20px;">
                <?= Html::a('<span class="glyphicon glyphicon-pencil"></span>', ['user/update', 'id' => $model->id, 'containerPjaxReload' => '#pjax-user-info-container'], ['role' => 'modal-remote']) ?>
            </div>
        </div>
        <div class="panel-body">
 

            <div class="row">
                <div class="col-md-2">
                    <img src="<?=Url::toRoute(['/'.$model->realAvatar])?>" style="width: 100%; height: 100%; object-fit: cover;">
                </div>
                <div class="col-md-10">
                    <?= DetailView::widget([
                    'model' => $model,
                    'attributes' => [
                        'name',
                        'login:email',
                        'birth_date',
                        'phone',
                        'info'
                    ],
                    ]) ?>
                </div>



            </div>



        </div>




    </div>

</div>
<?php Pjax::end(); ?>
<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    'options' => ['class' => 'fade modal-slg'],
    "footer"=>"",// always need it for jquery plugin
])?>
<?php Modal::end(); ?>